version: "3.7"

services:
  sln-dev:
    build: .
    image: node:12-alpine
    command: sh -c "npm install && npm run build"
    ports:
      - "80:3005"
    working_dir: /similar-listings-and-news
    volumes:
      - ./:/similar-listings-and-news
    restart: always
    env_file:
      - .env.docker
    networks:
      - sln-network
    command: sh -c "npm prune --production"
    command: sh -c "npm run seed && npm run start:dev"
  mongo:
    image: mongo:4.2.8
    volumes:
      - sln-mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: reburke
      MONGO_INITDB_ROOT_PASSWORD: sln
    networks:
      - sln-network

volumes:
  sln-mongo-data:

networks:
  sln-network:
    driver: bridge
