version: 2.1
jobs:
    build_and_save:
        docker:
        - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - store_artifacts:
                path: coverage
workflows:
    version: 2.1
    main:
        jobs:
            - build_and_save