version: 2.1
jobs:
    test_and_coverage:
        docker:
        - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
            - run: npm test
            - store_artifacts:
                path: coverage
workflows:
    version: 2.1
    main:
        jobs:
            - test_and_coverage
